### ISSUE TITLE
Add InstrumentSensitivity support to ChannelResponseFilter

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#16]
In order to support mapping mth5 metadata to StationXML we need to be able to generate the 
<InstrumentSensitivity>
</InstrumentSensitivity>
xml block.  

This is a "grand total" for all filter stages in a channel and thus belonds in the ChannelResponseFilter() class

**Comment by kujaku11** [comment]
@kkappler I added a function to ChannelResponseFilter that will estimate the instrument sensitivity for a given normalization frequency.  And added a validator and some logic for units consistency.  The sensitivity is slightly off from what is in the original stationxml, but not much.  For the magnetic channel the original is 100 and the computed is 100.99.  Not sure if that is an our error or an error in the original.

**Comment by kkappler** [comment]
This is now returning 100 (to within 6 sigfig)

**Comment by kkappler** [comment]
The electric field response was showing 4 orders difference -- debug that

**Comment by kujaku11** [comment]
@kkappler I have a suspicion that the instrument sensitivity in the xml files we have for electric channels are incorrect.  Because I have 2 files with the same electric filters but 2 different instrument sensitivities.  The one pulled off the DMC is 4.45955004E10 and the one from Anna is 40960000000.  Both are estimated at 0.01 Hz.  I don't see how they get these values from the normalization factors and gains that are in the electric filters, can you?

**Comment by kujaku11** [comment]
@kkappler FIXED: Need to use total_gain in the ZPK filter then the numbers come out correctly
