### ISSUE TITLE
Failure to install lxml breaks build on gh actions

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#184]
See [aurora issue # 313](https://github.com/simpeg/aurora/issues/313)

It looks like something has updated with lxml and python 3.8 & 3.9 are not able to build our environment.

Here is a [gh actions test that failed Dec 29 ](https://github.com/kujaku11/mt_metadata/actions/runs/7294036756/job/20036264609)
 But the same test passed around a week ago.

**Comment by kkappler** [comment]
@kujaku11 can you please add [https://github.com/laura-iris](https://github.com/laura-iris) to mt_metadata with push permission in order to test branch `fix_issue_184`?

**Comment by laura-iris** [comment]
lxml is being installed through obspy and isn't pinned to a specific version there. Today lxml released version 5.0.0, which explains the change in behavior today. I haven't had time to look much further than that, but I'll get back to it next week.

**Comment by laura-iris** [comment]
@kkappler I don't have the permissions to restart the 3.8 pipeline in mt_metadata, but I do see that you have one in aurora that passed about an hour ago. It looks like it handled lxml v5.0.0 just fine in that case: https://github.com/simpeg/aurora/actions/runs/7402625504/job/20140872929 

Makes me wonder if it was an issue with the new release that has since been dealt with?

**Comment by kujaku11** [comment]
@laura-iris I just added you as a collaborator.

**Comment by kujaku11** [comment]
@kkappler @laura-iris Looks like the issue was fixed, all tests pass now.  Gonna close this issue for now.
