### ISSUE TITLE
Creating FAP Filter

### ISSUE THREAD

**Issue by kujaku11** [kujaku11/mt_metadata#54]
I cloned your main branch, installed mt-metadata using the setup.py file and tried to create a frequency_response_table_filter and convert my filter to an ObsPy stage. I ran into the following error:
```
---------------------------------------------------------------------------
	IndexError                                Traceback (most recent call last)
	/var/folders/pn/k5blhlvd7vzdfy85t2z3_h940000gn/T/ipykernel_1237/2779005987.py in <module>
	----> 1 bx_filter.to_obspy()
	
	~/Downloads/mt_metadata-main/mt_metadata/timeseries/filters/channel_response_filter.py in to_obspy(self, sample_rate)
	    291 
	    292         """
	--> 293         total_sensitivity = self.compute_instrument_sensitivity()
	    294 
	    295         total_response = inventory.Response()
	
	~/Downloads/mt_metadata-main/mt_metadata/timeseries/filters/channel_response_filter.py in compute_instrument_sensitivity(self, normalization_frequency)
	    245             sensitivity *= complex_response
	    246         try:
	--> 247             return np.round(np.abs(sensitivity[0]), 3)
	    248         except TypeError:
	    249             return np.round(np.abs(sensitivity), 3)	
IndexError: invalid index to scalar variable.
```
I updated my local copy of your branch with the following fix: `except IndexError` (line 248) and was able to convert my filter to an ObsPy stage. Not a big deal but I just wanted to bring it up in case it would be helpful.

**Comment by MaevaP** [comment]
Here is the workflow that I followed to create a frequency table filter and convert the created filter to an ObsPy stage.

```
import numpy as np
import os

from mt_metadata.timeseries.filters.frequency_response_table_filter import FrequencyResponseTableFilter
from mt_metadata.timeseries.filters.channel_response_filter import ChannelResponseFilter

fap_filter = FrequencyResponseTableFilter(name='correction_factor_bx',
                                          units_in='nT',
                                          units_out='nT',
                                          comments='Frequency dependent correction for magnetic field')

path2cal = '/Users/maevapourpoint/PASSCAL/Software/LEMI/Calibration_files/rsp_LEMI-424_N131to145/'

bx_cal_file = os.path.join(path2cal, 'LEMI-424_N131_Bx.rsp')
frequencies = []
amplitudes = []
phases = []
with open(bx_cal_file, 'r') as fin:
    for line in fin:
        frequency, amplitude, phase = line.strip().split()
        frequencies.append(float(frequency))
        amplitudes.append(float(amplitude))
        phases.append(float(phase))
fap_filter.frequencies = np.array(frequencies, dtype=float)
fap_filter.amplitudes = np.array(amplitudes, dtype=float)
fap_filter.phases = np.deg2rad(phases, dtype=float)

bx_filter = ChannelResponseFilter(filters_list=[fap_filter])

bx_response = bx_filter.to_obspy()
```

Find attached the calibration file (FAP table) I used as input. In this file, the responses of the logger and sensor (fluxgate in this case) are combined.
[LEMI-424_N131_Bx.rsp.zip](https://github.com/kujaku11/mt_metadata/files/7016441/LEMI-424_N131_Bx.rsp.zip)

In this case, I am trying to create a single stage response since the LEMI logger "internally corrects" the recorded signal and outputs physical units (nT for the Hx channel). This single stage response would be equivalent to a frequency-dependent correction factor that one would have to apply to the data to account/correct for some assumptions made by the LEMI manufacturers that don't hold as we get closer to Nyquist (i.e., unit gain and zero phase).

The computed instrument sensitivity (line 245) is: (0.998636015619-0.00840646933685j)

Let me know if you need additional details.

**Comment by kujaku11** [comment]
@MaevaP I replicated the bug.  Thanks for the find.

Added IndexError to the exception list in line 248 of channel_response_filter.py.  Which should fix the issue.

The instrument sensitivity looks close to correct basically 1 at 0.04 Hz.  

Reopen this if that did not fix the issue.

**Comment by MaevaP** [comment]
@kujaku11
Just tested your fix and it works. Thank you for the quick turnaround.
